# Generated by Django 3.2.8 on 2021-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20211023_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
