# Generated by Django 3.2.8 on 2021-10-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='recent_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='singlechat',
            name='recent_msg',
            field=models.TextField(blank=True),
        ),
    ]
